emp/emp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.homepage),
    path("about/",views.about),
    path('employees/',include('employee.urls'))
]

emp/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee_dir'

urlpatterns = [
    path('', views.employee_list , name="list"),
    path('create/', views.employee_create, name='create'),
    path('update/<path:slug>', views.employee_update, name='update'),
    path('delete/<path:slug>', views.employee_delete, name='delete'),
    path('<path:slug>', views.employee_page, name="page"),  
]

emp/employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

emp/employee/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'border border-gray-300 rounded-lg p-2 w-full'}),
            'last_name': forms.TextInput(attrs={'class': 'border border-gray-300 rounded-lg p-2 w-full'}),
            'email': forms.EmailInput(attrs={'class': 'border border-gray-300 rounded-lg p-2 w-full'}),
        }

emp/emp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,"home.html")

def about(request):
    return render(request,'about.html')

emp/employee/views.py
from django.shortcuts import render, redirect
from .models import Employee
from .forms import EmployeeForm
import logging

Logger = logging.getLogger(__name__)


# Create your views here.
def employee_list(request):
    employees = Employee.objects.all()
    return render(request, 'employees/employee_list.html', {'employees': employees})


def employee_page(request, slug):
    employee = Employee.objects.get(email=slug)
    return render(request, 'employees/employee_page.html', {'employee': employee})

def employee_create(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            Logger.debug("Form is Valid")
            form.save()
            Logger.info("Employee added")
            return redirect('employee_dir:list')
    else:
        form = EmployeeForm()
    return render(request, 'employees/employee_form.html', {'form': form})

def employee_update(request, slug):
    employee = Employee.objects.get(email=slug)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            Logger.info("Form is Valid")
            form.save()
            return redirect('employee_dir:list')
    else:
        form = EmployeeForm(instance=employee)
    return render(request, 'employees/employee_update_form.html', {'form': form})

def employee_delete(request, slug):
    employee = Employee.objects.get(email=slug)
    if request.method == 'POST':
        employee.delete()
        return redirect('employee_dir:list')
    return render(request, 'employees/employee_confirm_delete.html', {'employee': employee})
    
    

emp/employee/templates/employees/employee_confirm_delete.html
{% extends 'layout.html' %} 
{% block title %}
    {{ employee.first_name }} {{employee.last_name}} 
{% endblock %}

{% block content %}
    <section  class="p-8 flex flex-col items-center justify-center w-screen">
        <h1 class="text-2xl font-bold mb-6">Delete Employee</h1>
        <p>Are you sure you want to delete {{ employee.first_name }} {{ employee.last_name }}?</p>
        <form method="post" class=" mx-auto">
            {% csrf_token %}
            <button type="submit"class="text-white bg-red-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Yes, Delete</button>
        </form>
        <a href="{% url 'employee_dir:list' %}">Cancel</a>

    </section>
{% endblock %}

emp/employee/templates/employees/employee_form.html
{% extends 'layout.html' %} {% block title %}Employee Create{% endblock %} 
{% block content %}
<section class="p-8 flex flex-col items-center justify-center w-screen">
  <h1 class="text-2xl font-bold mb-6">Employee Create</h1>

  <form method="post" class="w-[40%] mx-auto">
    {% csrf_token %}

    <div class="mb-5">
      <label
        for="id_first_name"
        class="block mb-2 text-sm font-medium text-gray-900"
      >
        First Name
      </label>
      {{ form.first_name }}
    </div>

    <div class="mb-5">
      <label
        for="id_last_name"
        class="block mb-2 text-sm font-medium text-gray-900"
      >
        Last Name
      </label>
      {{ form.last_name }}
    </div>

    <div class="mb-5">
      <label
        for="id_email"
        class="block mb-2 text-sm font-medium text-gray-900"
      >
        Email
      </label>
      {{ form.email }}
    </div>

    <button
      type="submit"
      class="text-white bg-green-400 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
    >
      Submit
    </button>
  </form>
</section>
{% endblock %}

emp/employee/templates/employees/employee_list.html
{% extends 'layout.html' %} {% block title %} Employees {% endblock %}

{% block content %}
<section class="p-8">
  <h1 class="text-2xl font-bold mb-6">Employee List</h1>

  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">First name</th>
          <th scope="col" class="px-6 py-3">Last name</th>
          <th scope="col" class="px-6 py-3">Email</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr class="bg-white border-b border-gray-200">
          <th
            scope="row"
            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap"
          >
            {{ employee.first_name }}
          </th>
          <td class="px-6 py-4">{{ employee.last_name }}</td>
          <td class="px-6 py-4">
            <a
              href="{% url 'employee_dir:page' slug=employee.email %}"
              class="text-blue-600 hover:underline"
            >
              {{ employee.email }}</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <a href="{% url 'employee_dir:create' %}">
    <button
      type="button"
      class="text-white bg-green-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 my-2"
    >
      Create New
    </button>
  </a>
</section>
{% endblock %}

emp/employee/templates/employees/employee_page.html
{% extends 'layout.html' %} 
{% block title %}
    {{ employee.first_name }} {{employee.last_name}}
{% endblock %}

{% block content %}
    <section class="p-8 flex flex-col items-center justify-center w-screen">
    <div
        class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-sm"
    >
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">
        {{ employee.first_name }} {{employee.last_name}}
        </h5>
        <p class="mb-3 font-normal text-gray-700">{{ employee.email }}</p>
        <div class="flex gap-4 justify-between">
        <a href="{% url 'employee_dir:update' slug=employee.email %}">
            <button
            type="button"
            class="text-white bg-green-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 my-2"
            >
            Edit
            </button>
        </a>
        <a href="{% url 'employee_dir:delete' slug=employee.email %}">
            <button
            type="button"
            class="text-white bg-red-500 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 my-2"
            >
            Delete
            </button>
        </a>
        </div>
    </div>
    </section>
{% endblock %}

emp/employee/templates/employees/employee_update_form.html
{% extends 'layout.html' %} {% block title %} Employee {% endblock %} 

{% block content %}
<section class="p-8 flex flex-col items-center justify-center w-screen">
  <h1 class="text-2xl font-bold mb-6">Employee Update</h1>

  <form method="post" class="w-[40%] mx-auto">
    {% csrf_token %}
    <div class="mb-5">
      <label
        for="id_first_name"
        class="block mb-2 text-sm font-medium text-gray-900"
      >
        First Name
      </label>
      {{ form.first_name }}
    </div>

    <div class="mb-5">
      <label
        for="id_last_name"
        class="block mb-2 text-sm font-medium text-gray-900"
      >
        Last Name
      </label>
      {{ form.last_name }}
    </div>

    <div class="mb-5">
      <label
        for="id_email"
        class="block mb-2 text-sm font-medium text-gray-900"
      >
        Email
      </label>
      {{ form.email }}
    </div>
    <button
      type="submit"
      class="text-white bg-green-400 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
    >
      Update
    </button>
  </form>
</section>
{% endblock %}

emp/templates/home.html
{% extends 'layout.html' %} 
{% block title %} Home {% endblock %} 
{% block content %}
  <section class="p-4 flex flex-col items-center justify-center">
    <h1>Welcome to the Employee Directory</h1>
    <p>This is a simple application to manage employee records.</p>
    <a href="{% url 'employee_dir:list' %}" class="text-blue-400">View Employees</a>
    <a href="/admin" class="text-blue-400 ">Admin Panel</a>
  </section>
{% endblock %}

emp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Django App {% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  </head>
  <body>
    <nav class="bg-green-400 text-white p-4 flex gap-6">
      <a href="/"> Home </a>
      <a href="{% url 'employee_dir:list' %}"> Employees </a>
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>